name = "fell-x27/empowa_swap"
version = "0.0.1"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'fell-x27/empowa_swap'"

[repository]
user = "fell-x27"
project = "empowa_swap"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config.default]
contract_treasury_marker_name = "TRS"
contract_treasury_lovelace = 5_000_000
contract_exchange_start_after = 1_234_567
contract_treasury_base_quantity = 11_000
