name = "fell-x27/empowa_swap"
version = "1.0"
compiler = "v1.1.17"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contract for project 'fell-x27/empowa_swap'"

[repository]
user = "fell-x27"
project = "empowa_swap"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config.default]
contract_treasury_marker_name = "TRS"
contract_treasury_lovelace_quantity = 5_000_000
contract_treasury_asset_quantity = 11_000
payout_asset_name = "EMP"
burn_nft_name = "Empowa Collateral v1.2"
n2a_change_rate = 1100
start_change_time = 1751659300246
unlock_unclaimed_assets_time = 1751659613763

[config.default.burn_nft_pid]
bytes = "94a8c6dd914997d05bc03ec3d550d84ca8b4b9ed965da0f67e31663c"
encoding = "hex"

[config.default.payout_asset_pid]
bytes = "3c72f5fd7ef47230f81dd3488f700b0d9cc63c7d8405b385883ecb20"
encoding = "hex"

[config.default.owner_key_hash]
bytes = "b03f1794dfca5968fb916eed4f31f627a133ea8ed3054302191a0526"
encoding = "hex"

[config.mainnet]
contract_treasury_marker_name = "TRS"
contract_treasury_lovelace_quantity = 5_000_000
contract_treasury_asset_quantity = 11_000
payout_asset_name = "EMP"
burn_nft_name = "Empowa Collateral v1.2"
n2a_change_rate = 1100
start_change_time = 1765998000000
unlock_unclaimed_assets_time = 1797534000000

[config.mainnet.burn_nft_pid]
bytes = "a8b19200b182a42099087f366cb7a36f5f37ac25e8fd8e04e6b147f7"
encoding = "hex"

[config.mainnet.payout_asset_pid]
bytes = "6c8642400e8437f737eb86df0fc8a8437c760f48592b1ba8f5767e81"
encoding = "hex"

[config.mainnet.owner_key_hash]
bytes = "b03f1794dfca5968fb916eed4f31f627a133ea8ed3054302191a0526"
encoding = "hex"


